In [1]:
import numpy as np
#create a 1D array
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [2]:
#accessing elements from the array
arr1[2]

3

In [3]:
#change elements from the array(modify the value of array item)
arr1[2]=5
arr1

array([1, 2, 5])

In [4]:
#create a 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
#check the shape of the array
print(" The shape is 2 rows and 3 columns:",arr2.shape)

 The shape is 2 rows and 3 columns: (2, 3)


In [6]:
#Accessing elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [7]:
#Array of type string
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [8]:
arr3[1]

'China'

In [30]:
#Array of evenly spaced values within a specified interval
arr=np.arange(0,21,4)
print(arr)

[ 0  4  8 12 16 20]


In [10]:
#Array of evenly spaced number in a specified interval 
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [11]:
#Array of random values between 0 and 1 in a given shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.51125916 0.14528165 0.97220025 0.05734834 0.9739647  0.13839241
 0.89519663 0.97388194 0.76532377 0.2789623 ]


[[0.32083743 0.17419584 0.80685004 0.72949183]
 [0.63735649 0.15076693 0.29729813 0.42579388]
 [0.08673885 0.5803334  0.99754385 0.30299886]]


In [12]:
#Array of constant values in a given shape
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [13]:
#create an array by repetition
#repeat each element of an array by a specified number of times
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [14]:
#Repeat an array by a specified number of times
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [15]:
#create an identity matrix
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
arr=np.random.rand(5,5)
print(arr)

[[0.72095106 0.34876326 0.2873885  0.52160679 0.56151778]
 [0.82840106 0.26076968 0.40523873 0.59448155 0.11921576]
 [0.24347891 0.76241947 0.60608072 0.53748393 0.64301662]
 [0.09432823 0.62145212 0.91785856 0.05297889 0.0962568 ]
 [0.9747102  0.58689959 0.20814407 0.88628073 0.13276072]]


In [18]:
#sum along the column
print(np.sum(arr,axis=0))

[2.86186947 2.58030413 2.42471059 2.5928319  1.55276768]


In [19]:
#sum along the row
print(np.sum(arr,axis=1))

[2.44022738 2.20810679 2.79247967 1.78287461 2.78879532]


In [20]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.48049935075534683
0.5374839342416532
0.277583972941706
0.07705286203410176


In [21]:
#Sort an array
arr=np.random.rand(5,5)
print(arr)

[[0.03902506 0.15818155 0.20556977 0.38211999 0.1586422 ]
 [0.1134791  0.99522646 0.13483603 0.72829272 0.4041504 ]
 [0.27471782 0.39968429 0.91920271 0.0319274  0.57094049]
 [0.05634687 0.51000061 0.36388151 0.21629365 0.75512047]
 [0.21503846 0.83003947 0.62947198 0.6255635  0.79107882]]


In [22]:
#sort along the row
print(np.sort(arr,axis=1))

[[0.03902506 0.15818155 0.1586422  0.20556977 0.38211999]
 [0.1134791  0.13483603 0.4041504  0.72829272 0.99522646]
 [0.0319274  0.27471782 0.39968429 0.57094049 0.91920271]
 [0.05634687 0.21629365 0.36388151 0.51000061 0.75512047]
 [0.21503846 0.6255635  0.62947198 0.79107882 0.83003947]]


In [23]:
#Append elements to an array
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [24]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [25]:
#Delete multiple elements
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [26]:
#combine and split an array
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

#combine the array items by column
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [27]:
#combine array items by row
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
